<?php
$items = [
    [
        "number" => 1,
        "question" => "SIMPATI",
        "options" => [
            ["option"=>"Suka", "isTrue"=>0],
            ["option"=>"Iri", "isTrue"=>0],
            ["option"=>"Jahat", "isTrue"=>0],
            ["option"=>"Sombong", "isTrue"=>0],
            ["option"=>"Benci", "isTrue"=>1],
        ],
    ],
    [
        "number" => 2,
        "question" => "NODA",
        "options" => [
            ["option"=>"Kotor", "isTrue"=>0],
            ["option"=>"Cuci", "isTrue"=>0],
            ["option"=>"Suci", "isTrue"=>1],
            ["option"=>"Sabun", "isTrue"=>0],
            ["option"=>"Rapi", "isTrue"=>0],
        ],
    ],
    [
        "number" => 3,
        "question" => "FENOMENA",
        "options" => [
            ["option"=>"Kejadian", "isTrue"=>0],
            ["option"=>"Peristiwa", "isTrue"=>0],
            ["option"=>"Ramalan", "isTrue"=>0],
            ["option"=>"Angan-angan", "isTrue"=>1],
            ["option"=>"Prinsip", "isTrue"=>0],
        ],
    ],
    [
        "number" => 4,
        "question" => "BELIA",
        "options" => [
            ["option"=>"Dewasa", "isTrue"=>0],
            ["option"=>"Yunior", "isTrue"=>0],
            ["option"=>"Senior", "isTrue"=>1],
            ["option"=>"Kakak", "isTrue"=>0],
            ["option"=>"Balita", "isTrue"=>0],
        ],
    ],
    [
        "number" => 5,
        "question" => "WEDANA",
        "options" => [
            ["option"=>"Bupati", "isTrue"=>0],
            ["option"=>"Camat", "isTrue"=>1],
            ["option"=>"Lurah", "isTrue"=>0],
            ["option"=>"Kabupaten", "isTrue"=>0],
            ["option"=>"Pendopo", "isTrue"=>0],
        ],
    ],
    [
        "number" => 6,
        "question" => "TESTAMEN",
        "options" => [
            ["option"=>"Wasiat", "isTrue"=>0],
            ["option"=>"Warisan", "isTrue"=>0],
            ["option"=>"Ramalan", "isTrue"=>0],
            ["option"=>"Tidak berpesan", "isTrue"=>1],
            ["option"=>"Ahli waris", "isTrue"=>0],
        ],
    ],
    [
        "number" => 7,
        "question" => "TERATUR",
        "options" => [
            ["option"=>"Rapi", "isTrue"=>0],
            ["option"=>"Rusuh", "isTrue"=>0],
            ["option"=>"Sistematik", "isTrue"=>0],
            ["option"=>"Terarah", "isTrue"=>0],
            ["option"=>"Ruwet", "isTrue"=>1],
        ],
    ],
    [
        "number" => 8,
        "question" => "STABIL",
        "options" => [
            ["option"=>"Normal", "isTrue"=>0],
            ["option"=>"Labil", "isTrue"=>1],
            ["option"=>"Tenang", "isTrue"=>0],
            ["option"=>"Seimbang", "isTrue"=>0],
            ["option"=>"Anomali", "isTrue"=>0],
        ],
    ],
    [
        "number" => 9,
        "question" => "SIGNIFIKAN",
        "options" => [
            ["option"=>"Berarti", "isTrue"=>0],
            ["option"=>"Penting", "isTrue"=>0],
            ["option"=>"Tak berarti", "isTrue"=>1],
            ["option"=>"Menang", "isTrue"=>0],
            ["option"=>"Dekat", "isTrue"=>0],
        ],
    ],
    [
        "number" => 10,
        "question" => "SAHIH",
        "options" => [
            ["option"=>"Sah", "isTrue"=>0],
            ["option"=>"Wajib", "isTrue"=>0],
            ["option"=>"Sempurna", "isTrue"=>0],
            ["option"=>"Cacat", "isTrue"=>1],
            ["option"=>"Benar", "isTrue"=>0],
        ],
    ],
    [
        "number" => 11,
        "question" => "STAGNAN",
        "options" => [
            ["option"=>"Progresif", "isTrue"=>1],
            ["option"=>"Konstan", "isTrue"=>0],
            ["option"=>"Berhenti", "isTrue"=>0],
            ["option"=>"Baku", "isTrue"=>0],
            ["option"=>"Aktif", "isTrue"=>0],
        ],
    ],
    [
        "number" => 12,
        "question" => "OPTIMIS",
        "options" => [
            ["option"=>"Peragu", "isTrue"=>0],
            ["option"=>"Putus Asa", "isTrue"=>0],
            ["option"=>"Pesimis", "isTrue"=>1],
            ["option"=>"Rendah hati", "isTrue"=>0],
            ["option"=>"Gairah", "isTrue"=>0],
        ],
    ],
    [
        "number" => 13,
        "question" => "KESEMPATAN",
        "options" => [
            ["option"=>"Peluang", "isTrue"=>0],
            ["option"=>"Ancaman", "isTrue"=>0],
            ["option"=>"Kemungkinan", "isTrue"=>0],
            ["option"=>"Keadaan", "isTrue"=>0],
            ["option"=>"Hambatan", "isTrue"=>1],
        ],
    ],
    [
        "number" => 14,
        "question" => "PARADOKS",
        "options" => [
            ["option"=>"Kebaikan", "isTrue"=>0],
            ["option"=>"Berbeda", "isTrue"=>0],
            ["option"=>"Bertentangan", "isTrue"=>0],
            ["option"=>"Selaras", "isTrue"=>1],
            ["option"=>"Kenyataan", "isTrue"=>0],
        ],
    ],
    [
        "number" => 15,
        "question" => "SETELAH",
        "options" => [
            ["option"=>"Pra", "isTrue"=>1],
            ["option"=>"Akan", "isTrue"=>0],
            ["option"=>"Pasca", "isTrue"=>0],
            ["option"=>"Melintas", "isTrue"=>0],
            ["option"=>"Sudah", "isTrue"=>0],
        ],
    ],
    [
        "number" => 16,
        "question" => "PAKAR",
        "options" => [
            ["option"=>"Spesialis", "isTrue"=>0],
            ["option"=>"Perintis", "isTrue"=>0],
            ["option"=>"Pioner", "isTrue"=>0],
            ["option"=>"Awam", "isTrue"=>1],
            ["option"=>"Ahli", "isTrue"=>0],
        ],
    ],
    [
        "number" => 17,
        "question" => "ORTODOKS",
        "options" => [
            ["option"=>"Kuno", "isTrue"=>0],
            ["option"=>"Mutakhir", "isTrue"=>1],
            ["option"=>"Sekte", "isTrue"=>0],
            ["option"=>"Kolot", "isTrue"=>0],
            ["option"=>"Dahulu", "isTrue"=>0],
        ],
    ],
    [
        "number" => 18,
        "question" => "NORMAL",
        "options" => [
            ["option"=>"Sinkron", "isTrue"=>0],
            ["option"=>"Tanpa cacat", "isTrue"=>0],
            ["option"=>"Anomali", "isTrue"=>1],
            ["option"=>"Waras", "isTrue"=>0],
            ["option"=>"Sesuai", "isTrue"=>0],
        ],
    ],
    [
        "number" => 19,
        "question" => "NISBI",
        "options" => [
            ["option"=>"Relatif", "isTrue"=>0],
            ["option"=>"Mutlak", "isTrue"=>1],
            ["option"=>"Abstrak", "isTrue"=>0],
            ["option"=>"Tergantung", "isTrue"=>0],
            ["option"=>"Usaha", "isTrue"=>0],
        ],
    ],
    [
        "number" => 20,
        "question" => "NETRAL",
        "options" => [
            ["option"=>"Abstain", "isTrue"=>0],
            ["option"=>"Berpihak", "isTrue"=>1],
            ["option"=>"Sejalan", "isTrue"=>0],
            ["option"=>"Tidak terikat", "isTrue"=>0],
            ["option"=>"Koalisi", "isTrue"=>0],
        ],
    ],
    [
        "number" => 21,
        "question" => "BERANI",
        "options" => [
            ["option"=>"Garang", "isTrue"=>0],
            ["option"=>"Gentar", "isTrue"=>1],
            ["option"=>"Nekat", "isTrue"=>0],
            ["option"=>"Sabar", "isTrue"=>0],
            ["option"=>"Tegar", "isTrue"=>0],
        ],
    ],
    [
        "number" => 22,
        "question" => "MITRA",
        "options" => [
            ["option"=>"Bagian", "isTrue"=>0],
            ["option"=>"Kompetitor", "isTrue"=>1],
            ["option"=>"Serikat", "isTrue"=>0],
            ["option"=>"Teman", "isTrue"=>0],
            ["option"=>"Akrab", "isTrue"=>0],
        ],
    ],
    [
        "number" => 23,
        "question" => "MENYAMBUNG",
        "options" => [
            ["option"=>"Meneruskan", "isTrue"=>0],
            ["option"=>"Merangkai", "isTrue"=>0],
            ["option"=>"Memotong", "isTrue"=>1],
            ["option"=>"Menyulam", "isTrue"=>0],
            ["option"=>"Partisipasi", "isTrue"=>0],
        ],
    ],
    [
        "number" => 24,
        "question" => "MENTAL",
        "options" => [
            ["option"=>"Jiwa", "isTrue"=>0],
            ["option"=>"Sikap", "isTrue"=>0],
            ["option"=>"Raga", "isTrue"=>1],
            ["option"=>"Watak", "isTrue"=>0],
            ["option"=>"Pikiran", "isTrue"=>0],
        ],
    ],
    [
        "number" => 25,
        "question" => "MAYOR",
        "options" => [
            ["option"=>"Perwira tinggi", "isTrue"=>0],
            ["option"=>"Minor", "isTrue"=>1],
            ["option"=>"Tenor", "isTrue"=>0],
            ["option"=>"Alto", "isTrue"=>0],
            ["option"=>"Banyak", "isTrue"=>0],
        ],
    ],
    [
        "number" => 26,
        "question" => "MAKAR",
        "options" => [
            ["option"=>"Akal busuk", "isTrue"=>0],
            ["option"=>"Berpihak", "isTrue"=>1],
            ["option"=>"Teroris", "isTrue"=>0],
            ["option"=>"Tipu muslihat", "isTrue"=>0],
            ["option"=>"Anarki", "isTrue"=>0],
        ],
    ],
    [
        "number" => 27,
        "question" => "KUANTITAS",
        "options" => [
            ["option"=>"Mutu", "isTrue"=>1],
            ["option"=>"Jaminan", "isTrue"=>0],
            ["option"=>"Kuintal", "isTrue"=>0],
            ["option"=>"Jumlah", "isTrue"=>0],
            ["option"=>"Realitas", "isTrue"=>0],
        ],
    ],
    [
        "number" => 28,
        "question" => "KONTRADIKSI",
        "options" => [
            ["option"=>"Selaras", "isTrue"=>1],
            ["option"=>"Ambigu", "isTrue"=>0],
            ["option"=>"Seimbang", "isTrue"=>0],
            ["option"=>"Pertentangan", "isTrue"=>0],
            ["option"=>"Perbedaan", "isTrue"=>0],
        ],
    ],
    [
        "number" => 29,
        "question" => "BERUBAH",
        "options" => [
            ["option"=>"Konstan", "isTrue"=>1],
            ["option"=>"Progresif", "isTrue"=>0],
            ["option"=>"Spekulatif", "isTrue"=>0],
            ["option"=>"Asing", "isTrue"=>0],
            ["option"=>"Tukar", "isTrue"=>0],
        ],
    ],
    [
        "number" => 30,
        "question" => "ABSTRAK",
        "options" => [
            ["option"=>"Maya", "isTrue"=>0],
            ["option"=>"Konkrit", "isTrue"=>1],
            ["option"=>"Kabur", "isTrue"=>0],
            ["option"=>"Visual", "isTrue"=>0],
            ["option"=>"Diagram", "isTrue"=>0],
        ],
    ],
    [
        "number" => 31,
        "question" => "KONDUKTOR",
        "options" => [
            ["option"=>"Perantara", "isTrue"=>0],
            ["option"=>"Penyelaras", "isTrue"=>0],
            ["option"=>"Penyalur", "isTrue"=>0],
            ["option"=>"Penghambat", "isTrue"=>1],
            ["option"=>"Karet", "isTrue"=>0],
        ],
    ],
    [
        "number" => 32,
        "question" => "INDIVIDUAL",
        "options" => [
            ["option"=>"Selektif", "isTrue"=>0],
            ["option"=>"Berkelompok", "isTrue"=>1],
            ["option"=>"Kolektif", "isTrue"=>1],
            ["option"=>"Mono", "isTrue"=>0],
            ["option"=>"Primordial", "isTrue"=>0],
        ],
    ],
    [
        "number" => 33,
        "question" => "KOHESI",
        "options" => [
            ["option"=>"Bebas", "isTrue"=>0],
            ["option"=>"Adhesi", "isTrue"=>1],
            ["option"=>"Keterikatan", "isTrue"=>0],
            ["option"=>"Hubungan", "isTrue"=>0],
            ["option"=>"Transfusi", "isTrue"=>0],
        ],
    ],
    [
        "number" => 34,
        "question" => "MINI",
        "options" => [
            ["option"=>"Jumbo", "isTrue"=>1],
            ["option"=>"Kecil", "isTrue"=>0],
            ["option"=>"Super", "isTrue"=>0],
            ["option"=>"Sedikit", "isTrue"=>0],
            ["option"=>"Mikro", "isTrue"=>0],
        ],
    ],
    [
        "number" => 35,
        "question" => "PERKENALAN",
        "options" => [
            ["option"=>"Pertemanan", "isTrue"=>0],
            ["option"=>"Introduksi", "isTrue"=>0],
            ["option"=>"Tanda-tanda", "isTrue"=>0],
            ["option"=>"Penutup", "isTrue"=>1],
            ["option"=>"Prakata", "isTrue"=>0],
        ],
    ],
    [
        "number" => 36,
        "question" => "KONTINU",
        "options" => [
            ["option"=>"Istimewa", "isTrue"=>0],
            ["option"=>"Rutin", "isTrue"=>0],
            ["option"=>"Khusus", "isTrue"=>0],
            ["option"=>"Insidental", "isTrue"=>1],
            ["option"=>"Tidak jadi", "isTrue"=>0],
        ],
    ],
    [
        "number" => 37,
        "question" => "HOMOGEN",
        "options" => [
            ["option"=>"Sejenis", "isTrue"=>0],
            ["option"=>"Harmonis", "isTrue"=>0],
            ["option"=>"Heterogen", "isTrue"=>1],
            ["option"=>"Multi", "isTrue"=>0],
            ["option"=>"Senyawa", "isTrue"=>0],
        ],
    ],
    [
        "number" => 38,
        "question" => "KONTAN",
        "options" => [
            ["option"=>"Gratis", "isTrue"=>0],
            ["option"=>"Bayar", "isTrue"=>0],
            ["option"=>"Hutang", "isTrue"=>1],
            ["option"=>"Tunai", "isTrue"=>0],
            ["option"=>"Deposit", "isTrue"=>0],
        ],
    ],
    [
        "number" => 39,
        "question" => "TANDUS",
        "options" => [
            ["option"=>"Berbatu", "isTrue"=>0],
            ["option"=>"Subur", "isTrue"=>1],
            ["option"=>"Kering", "isTrue"=>0],
            ["option"=>"Gersang", "isTrue"=>0],
            ["option"=>"Basah", "isTrue"=>0],
        ],
    ],
    [
        "number" => 40,
        "question" => "GASAL",
        "options" => [
            ["option"=>"Semester", "isTrue"=>0],
            ["option"=>"Ganjil", "isTrue"=>0],
            ["option"=>"Genap", "isTrue"=>1],
            ["option"=>"Caturwulan", "isTrue"=>0],
            ["option"=>"Mid-semester", "isTrue"=>0],
        ],
    ],
    [
        "number" => 41,
        "question" => "MONOLOG",
        "options" => [
            ["option"=>"Epilog", "isTrue"=>0],
            ["option"=>"Prolog", "isTrue"=>0],
            ["option"=>"Dialog", "isTrue"=>1],
            ["option"=>"Interaktif", "isTrue"=>0],
            ["option"=>"Trilogi", "isTrue"=>0],
        ],
    ],
    [
        "number" => 42,
        "question" => "KACAU",
        "options" => [
            ["option"=>"Rawan", "isTrue"=>0],
            ["option"=>"Normal", "isTrue"=>1],
            ["option"=>"Hancur", "isTrue"=>0],
            ["option"=>"Kusut", "isTrue"=>0],
            ["option"=>"Runyam", "isTrue"=>0],
        ],
    ],
    [
        "number" => 43,
        "question" => "IMITASI",
        "options" => [
            ["option"=>"Autentik", "isTrue"=>1],
            ["option"=>"Semu", "isTrue"=>0],
            ["option"=>"Palsu", "isTrue"=>0],
            ["option"=>"Orisinil", "isTrue"=>1],
            ["option"=>"Samak", "isTrue"=>0],
        ],
    ],
    [
        "number" => 44,
        "question" => "Rasa Kasih",
        "options" => [
            ["option"=>"Acuh", "isTrue"=>0],
            ["option"=>"Antipati", "isTrue"=>1],
            ["option"=>"Apatis", "isTrue"=>0],
            ["option"=>"Peduli", "isTrue"=>0],
            ["option"=>"Iba", "isTrue"=>0],
        ],
    ],
    [
        "number" => 45,
        "question" => "ANTAGONIS",
        "options" => [
            ["option"=>"Menurut", "isTrue"=>1],
            ["option"=>"Sejalan", "isTrue"=>0],
            ["option"=>"Selaras", "isTrue"=>0],
            ["option"=>"Seimbang", "isTrue"=>0],
            ["option"=>"Terbalik", "isTrue"=>0],
        ],
    ],
];
?>
